#!/bin/bash

# Remember to:
#    module load intel/composer_xe_2015_sp1.0.080
#    module load intel/mkl_libraries_from_composer_xe_2013_sp1
#    module load gcc/4.7.4


echo ""
echo ""
echo ""
echo ""



cores=8
 
cho ""
echo "********  Submitting job ********"


bsub -q short -n $cores -W 03:00 -R select[ib] -R "rusage[mem=100]"  -R "span[hosts=1]" -R select[model=Intel_EM64T]  ./a.out


echo ""
echo ""
echo "******** Showng the jobs list *******"
echo "(Wait for 5 sec)"
sleep 5 

bjobs


